services:
  - type: web
    name: sintiens-app
    runtime: node
    plan: free
    healthCheckPath: /api/ping
    buildCommand: npm run build
    startCommand: node dist-server/server.cjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: SITE_URL
        value: https://sintiens.duckdns.org
      - key: GEMINI_API_KEY
        sync: false # You will enter the value in the Render dashboard
